Setup and documentation on running this on my local machine + bonus chroma on AWS Fargate (optional)
knowit/cvhelper pull request #1
Opened 2023-12-12 20:43 UTC by janhenrik

I made this all work locally!

My version does not have the populate-script, it is embedded in get_cv.py.

See if you like it!

2023-12-13 10:44 UTC, A-Stangeland commented
1. Documentation looks great, very much appreciated! 
2. Cool that got it to deploy on AWS, I will review the code when I get time. I am not yet decided how we're going to structure the project, so we may wait a bit before adding this.
3. What is the reason for removing Poetry? I think poetry makes it easier to have reproducible environments compared to just using pip.

Thank you for the contribution!

2023-12-13 13:42 UTC, janhenrik commented
My bad. We should keep poetry, I will try to make it work with poetry before we merge - if you do not have the time.

2023-12-14 21:22 UTC, A-Stangeland requested changes
Docuentation looks good. I don't know much about AWS infrastructure, but I saw some local paths that should be removed. I think we can merge in the updates to the documentation now, and create a new PR for the infrastructure code when it is ready.

2023-12-14 21:22 UTC, A-Stangeland commented on infrastructure/chroma-db-fargate/bin/python
Same as above, local path

2023-12-14 21:22 UTC, A-Stangeland commented on infrastructure/chroma-db-fargate/bin/pip
> +#!/Users/jhg/src/cvhelper/infrastructure/chroma-db-fargate/bin/python
This looks like a local path. Should probably not be included

2023-12-14 21:25 UTC, janhenrik commented on infrastructure/chroma-db-fargate/bin/pip
> +#!/Users/jhg/src/cvhelper/infrastructure/chroma-db-fargate/bin/python
Agree!

2023-12-14 21:26 UTC, janhenrik commented
Just remove the Infrastructure-folder/aws stuff, I will continue on that later.

2023-12-15 06:15 UTC, merged